### ISSUE TITLE
OpenSSL question

### ISSUE THREAD

**Issue by gurabli** [MatthewVance/nginx-build#12]
Hi,
great script, thanks! I see that you modified the original script, and OpenSSL is not built separately but you call it from nginx build directly with
`--with-openssl-opt="no-weak-ssl-ciphers no-ssl3 no-shared $ECFLAG -DOPENSSL_NO_HEARTBEATS -fstack-protector-strong" \`

As I see it is working fine, and OpenSSL is built with the options configured, and nginx is using this static OpenSSL build. I do have one question: 

OpennSSL complains that because of the configuration changes you need to do `make depend`, which is not included in the script if I'm not mistaken. The other scripts have it. Do you think it is a problem or not?

**Comment by MatthewVance** [comment]
Good question and I'd like to see the exact message if you captured it. 

Short answer is I don't *think* it matters. I'm also not sure it is possible when building it as part of NGINX because it wouldn't fit with with-openssl-opt and that's the only OpenSSL build control I'm aware of when doing it this way. If it's needed, I think NGINX would need to modify their install script to include it. 

I also checked OpenSSL documentation and it says "OpenSSL 1.1.0 and above performs the dependency step for you..." See https://wiki.openssl.org/index.php/Compilation_and_Installation#Dependencies for more.

Does this help? If you have ideas or are aware of specific problems, please let me know.

**Comment by gurabli** [comment]
Thanks for your reply! I think I know what is the problem: I was using a modified version of the script, where  I used the LTS version of OpenSSL, that is 1.0.2j. According to OpenSSL documentation: "If you are prompted to run make depend, then you must do so. For OpenSSL 1.0.2 and below, its required to update the standard distribution once configuration options change."

Consequently, if using the 1,1.0x branch (as you are using it in your script), then 'make depend' is no longer required, and the nginx configure options that you use are completely fine.
