### ISSUE TITLE
Restrict the regexes to certain versions

### ISSUE THREAD

**Issue by MatthewVance** [MatthewVance/nginx-build#78]
I'm wondering whether or not we should restrict the regexes to certain versions, e.g.
- PCRE 8.x,
- nginx 1.x.x,
- OpenSSL 1.1.x.

Just to be sure that if a new major version is released (or minor version in the case of OpenSSL), the script won't break because the compilation process has become out of date.

If the above isn't a valid concern, then in my opinion this pull request is ready to be merged.

_Originally posted by @jellemdekker in https://github.com/MatthewVance/nginx-build/pull/77#issuecomment-485546317_

**Comment by jellemdekker** [comment]
Example regexes:
```
pcre\-8\.[0-9]+
nginx\-1[0-9.]+[13579]\.[0-9]+
openssl\-1\.1\.[0-9]+[a-z]?
```

Tests via regexr (thanks @shmick for sample): [pcre](https://regexr.com/4coqj), [nginx](https://regexr.com/4coqa), [openssl](https://regexr.com/4coqs)

**Comment by shmick** [comment]
Would it make sense to have a`stable` option using the pinned versions, which would be the default, and a `latest` option that would always attempt to use the latest versions?

**Comment by jellemdekker** [comment]
I don't know if it would. To me this script's purpose is to provide a working release of the latest stable versions of nginx and OpenSSL (_stable_ meaning it excludes test-/pre-releases etc.). The issue at hand is that if OpenSSL 3.0.0 were to release right now, the regexes would use it instead of 1.1.x, and as a result the script would very likely break because of compilation changes for the new major version.

I'm sure that when OpenSSL 3.0.0 fully releases, after it has gone through its release candidates phase and all that, we will make sure to update this script to use that new major version as fast as we can. But that bump to a new major version should be something we do manually so we ensure that the version is ready for use in production environments and so that now and in the future, the script _just works_.

What are your thoughts on this?

**Comment by MatthewVance** [comment]
My intent with this script was to make it where everyone could always have the latest versions of NGINX and OpenSSL (stable/full release is what I had in mind). To that end, I don't think it makes sense to have stable and latest options. I also want to avoid the added complexity. 

At the same time, I think there is merit is limiting OpenSSL to 1.1.x. If/when another major version is released, we would manually test and update as quickly as we could. Major releases are historically not frequent and typically come with plenty of pre-releases so this shouldn't be a major burden. It should also increase the chances of the script continuing to *just* work.

**Comment by jellemdekker** [comment]
Hi @MatthewVance, did you decide on what to do with this issue?

**Comment by MatthewVance** [comment]
The original intent of this script was to make it where everyone could
always have the latest versions so I decided the restrictions weren't
necessary and closed the issue.
