### ISSUE TITLE
OpenSSL: No valid OpenPGP data found

### ISSUE THREAD

**Issue by GiovanniBattista** [MatthewVance/nginx-build#84]
I was trying to build nginx (once again) with this awesome script, as I encountered the following error:

```+ gpg --batch --verify openssl.tar.gz.asc openssl.tar.gz
gpg: no valid OpenPGP data found.
gpg: the signature could not be verified.
Please remember that the signature file (.sig or .asc)
should be the first file given on the command line.
```

First few lines of openssl.tar.gz.asc:
```<!DOCTYPE html>
<html lang="en">
<!-- head.inc -->
  <title>
  /err404.html
  </title>
  <meta charset="utf-8">
```

It appears, that the OpenSSL version could not be determined correctly. If you execute the `version_openssl` manually, the output is the following:
`openssl-3.0.0: ...`
Therefore, the tar and asc files were not found.

From [openssl.org/source](https://www.openssl.org/source/):
![image](https://user-images.githubusercontent.com/12544460/80279887-90f5d080-8700-11ea-927c-b8f15c985308.png)

**Comment by jellemdekker** [comment]
It seem the 3.0.0 alpha builds of OpenSSL are used, because the regular expression is not strict enough. I think this is fixed when we change it to: `openssl\-[0-9.]+[^\-]1[a-z]?` ([regexr example](https://regexr.com/53a33)).

@GiovanniBattista, can you change line 24 of your local copy of the script to the following and report back if it now uses OpenSSL 1.1.1g during building?
`version_openssl=$(curl -sL ${source_openssl} | grep -Eo 'openssl\-[0-9.]+[^\-]1[a-z]?' | sort -V | tail -n 1)`

**Comment by GiovanniBattista** [comment]
Yes, that works. Thanks.

I don't know about the OpenSSL version schema, but the following wouldn't work with this regex (due to the `1` in the regex, see this updated [regexr example](regexr.com/53a52)):
```
openssl-1.1.2.tar.gz
openssl-3.0.0a.tar.gz
```

**Comment by jellemdekker** [comment]
Good catch! I expanded the [test cases](https://regexr.com/53b8v) and have modified the regex to `openssl\-[0-9]+\.[0-9]+\.[0-9]+[a-z]?(?=\.tar\.gz)`. I'll make a pull request later today and run it by @MatthewVance.

**Comment by GainfulShrimp** [comment]
For me, the new regex didn't return results - thus the script would fail - until I also changed grep's pattern interpretation from `grep -Eo` (for extended regular expressions) to `grep -Po` (for Perl regular expressions). 
In case it helps, I'm using grep 3.3 on Raspbian Buster.
